### ISSUE TITLE
Despite having a character sheet with a designated portrait, no character portrait appears...

### ISSUE THREAD

**Issue by sunbeam60** [Heilemann/Realms#26]
[DD-character-sheet-5e-fillable.pdf](https://github.com/user-attachments/files/18085967/DD-character-sheet-5e-fillable.pdf)

![image](https://github.com/user-attachments/assets/dde722c1-b418-4830-8bfb-7ad1b797702e)
![image](https://github.com/user-attachments/assets/c3a928cc-9fe1-4088-a82e-d6d9c001ac55)

**Comment by Heilemann** [comment]
So two things. `CHARACTER IMAGE` is in fact not the place you put your image; instead it is an annotation in the box to the left, which isn't dealt with by my custom annotation image uploader logic thing; your image is in `Faction Symbol Image`; if you change to that I think it would work.

However, I did just fix it so the `CHARACTER IMAGE` will in fact work. It's an annotation type I hadn't seen before where for some reason a bunch of images are stacked on top of one another in a parent annotation. My solution isn't the neatest, but it works for now.
