### ISSUE TITLE
Target number dice rolles (e.g. /r 4d6#4) aren't working

### ISSUE THREAD

**Issue by sunbeam60** [Heilemann/Realms#39]
https://github.com/user-attachments/assets/cc1d2321-9267-4ed7-bcc0-6d7327a51981

**Comment by Heilemann** [comment]
Note to self: I think the target number syntax is wrong; IIRC it's supposed to be `1d20>10`

**Comment by sunbeam60** [comment]
But a target number is usually >= right?

Your target number is 5 on a d6 usually means 5 or 6. So then you'd have to do 3d6>3, which is odd when the target is 4. Unless you support 3d6>=4 or whatever.

**Comment by Heilemann** [comment]
https://wiki.roll20.net/Dice_Reference#Target_Number_.28Successes.29

Yes, mathematically, but the notation standard which was invented by Roll20 is just `1d20>10`.

**Comment by Heilemann** [comment]
I'll overhaul the UI; so this will go away soon.

**Comment by sunbeam60** [comment]
> https://wiki.roll20.net/Dice_Reference#Target_Number_.28Successes.29
> 
> 
> 
> Yes, mathematically, but the notation standard which was invented by Roll20 is just `1d20>10`.

🤯
