### ISSUE TITLE
Adding books to a game seems to hang (black screen)

### ISSUE THREAD

**Issue by sunbeam60** [Heilemann/Realms#4]
![image](https://github.com/user-attachments/assets/d6a55810-049a-481d-b502-10832769018a)

I presume the books you _can_ add are meant to come from your existing library.

**Comment by sunbeam60** [comment]
https://github.com/user-attachments/assets/c0b39f02-3caa-479d-8641-64db91ed723d

**Comment by Heilemann** [comment]
Fixed. Although I'm not shy to admit this bit needs to be overhauled, but it should work for now
