### ISSUE TITLE
When doing /r 3d6>6 and getting 0 successes, the chat shows nothing. However, if 1 or more success occur, chat shows x successes

### ISSUE THREAD

**Issue by sunbeam60** [Heilemann/Realms#44]
![image](https://github.com/user-attachments/assets/4eb15d71-469a-409a-854f-57a55952fd60)

**Comment by sunbeam60** [comment]
I would have expected "0 successes"

**Comment by Heilemann** [comment]
I made some improvements to this and will close it for now. I'll revisit the dice results later, probably many times. If you encounter specifics, please file new tickets!
