### ISSUE TITLE
When fumbles are rolled (skulls) in a big stack of dice, they overlap the dice above, making it unclear which dice they correspond to.

### ISSUE THREAD

**Issue by sunbeam60** [Heilemann/Realms#46]
![image](https://github.com/user-attachments/assets/c7546a6a-9b40-4514-aadf-cac7a7c46bdf)

**Comment by Heilemann** [comment]
I adjusted this a bit. Let me know if it’s unworkable for now; but I intend on coming back and making some updates to the dice results (in fact I made some updates yesterday; try clicking a die in the result)
