### ISSUE TITLE
Uploading a character sheet with no text (where images have been used instead of text) fails cryptically

### ISSUE THREAD

**Issue by sunbeam60** [Heilemann/Realms#5]
[Knave 2e Character Sheet by Jod v2.0 [FORM FILLABLE].pdf](https://github.com/user-attachments/files/18050144/Knave.2e.Character.Sheet.by.Jod.v2.0.FORM.FILLABLE.pdf)

This character sheet fails with this message:
![image](https://github.com/user-attachments/assets/de292c58-d8b2-41e0-a6c9-acab3a59c5ee)

**Comment by Heilemann** [comment]
@sunbeam60 Attach the sheet?

**Comment by sunbeam60** [comment]
Does the link in my original comment not work? If not lmk and I'll dig it up and attach it separately.

**Comment by Heilemann** [comment]
Ah, I had missed that. Thanks!

**Comment by Heilemann** [comment]
Alright, should be good. I did notice that with that sheet, the field names are essentially useless, so it's hard to map to the right field for name (and there's no image field for the portrait/token). Not sure whether I'll try to address that somehow. The other Pdfs I've been working with have been pretty good at field naming so might not be worth it.
