### ISSUE TITLE
When many books are in your library, it's not possible to see the full extent of the books in the book addition selector

### ISSUE THREAD

**Issue by sunbeam60** [Heilemann/Realms#52]
I can't scroll down on this list

https://github.com/user-attachments/assets/1fb3658c-a7bb-4656-92cd-aa5f34fb7158

**Comment by Heilemann** [comment]
Temporary fix going to prod now.

**Comment by sunbeam60** [comment]
![image](https://github.com/user-attachments/assets/8842d76b-60de-4abc-a5fa-57984443cfa9)

Still happening on Firefox
