### ISSUE TITLE
PDF forms can no longer been filled out (and previous values are gone)

### ISSUE THREAD

**Issue by sunbeam60** [Heilemann/Realms#53]
https://github.com/user-attachments/assets/075db45c-a681-4d8a-b86f-9a5b5237a3d7

**Comment by Heilemann** [comment]
Thanks. Looking at it now.

**Comment by Heilemann** [comment]
Alright, I believe it's been fixed. I see my Call of Cthulhu 7e reference sheet working perfectly, but I am having some issues with another sheet I just tried out, but I think it's probably an unrelated issue.
