### ISSUE TITLE
When editing a PDF sheet, the PDF fails to load

### ISSUE THREAD

**Issue by sunbeam60** [Heilemann/Realms#8]
![image](https://github.com/user-attachments/assets/bbb58d31-ca1c-4b4f-a140-cf38389d6877)

Firefox

**Comment by Heilemann** [comment]
Which PDF was this?

**Comment by sunbeam60** [comment]
[Knave.2e.Character.Sheet.by.Jod.v2.0.FORM.FILLABLE.pdf](https://github.com/user-attachments/files/18063337/Knave.2e.Character.Sheet.by.Jod.v2.0.FORM.FILLABLE.pdf)

**Comment by Heilemann** [comment]
Deploying fix.
